#!/usr/bin/env python3
"""
Generate rime/one.dict.yaml from font/one-pua-map.csv.

Reads the PUA mapping CSV and produces a Rime dictionary file with proper
YAML header and tab-separated entries.

Usage:
    python scripts/generate_dict.py

Paths are relative to the repository root. Run from the repo root or
the script will locate it automatically.
"""

import csv
import os
import sys
from datetime import date


def find_repo_root():
    """Walk up from the script location to find the repository root."""
    current = os.path.dirname(os.path.abspath(__file__))
    while current != os.path.dirname(current):
        if os.path.isfile(os.path.join(current, "README.md")) and os.path.isdir(
            os.path.join(current, "font")
        ):
            return current
        current = os.path.dirname(current)
    print("Error: Could not locate repository root.", file=sys.stderr)
    sys.exit(1)


def read_pua_map(csv_path):
    """Read the PUA map CSV and return a list of entry dicts.

    Skips comment lines (starting with #) and blank lines.
    Expected columns: codepoint, input, ipa, glyph_name
    """
    entries = []
    with open(csv_path, "r", encoding="utf-8") as f:
        reader = csv.DictReader(
            (row for row in f if row.strip() and not row.strip().startswith("#")),
            fieldnames=["codepoint", "input", "ipa", "glyph_name"],
        )
        for row in reader:
            # Skip the header row if it matches field names
            if row["codepoint"] == "codepoint":
                continue
            entries.append(row)
    return entries


def codepoint_to_char(hex_str):
    """Convert a hex codepoint string like '0xe010' to a Unicode character."""
    return chr(int(hex_str, 16))


def generate_dict_yaml(entries, output_path):
    """Write the Rime dictionary YAML file.

    Format:
        ---
        name: one
        version: "0.1.0"
        sort: by_weight
        ...

        <character>\t<input>\t<weight>
    """
    header = (
        "# Auto-generated by scripts/generate_dict.py\n"
        f"# Generated: {date.today().isoformat()}\n"
        f"# Source: font/one-pua-map.csv ({len(entries)} entries)\n"
        "#\n"
        "# Do not edit this file manually. Edit one-pua-map.csv and regenerate.\n"
        "\n"
        "---\n"
        "name: one\n"
        'version: "0.1.0"\n'
        "sort: by_weight\n"
        "columns:\n"
        "  - text\n"
        "  - code\n"
        "  - weight\n"
        "...\n"
        "\n"
    )

    lines = [header]
    weight = len(entries)  # Higher weight = higher priority; decrease as we go

    for entry in entries:
        char = codepoint_to_char(entry["codepoint"])
        input_code = entry["input"]
        lines.append(f"{char}\t{input_code}\t{weight}")
        weight -= 1

    with open(output_path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
        f.write("\n")

    return len(entries)


def main():
    repo_root = find_repo_root()
    csv_path = os.path.join(repo_root, "font", "one-pua-map.csv")
    output_path = os.path.join(repo_root, "rime", "one.dict.yaml")

    if not os.path.isfile(csv_path):
        print(f"Error: PUA map not found at {csv_path}", file=sys.stderr)
        sys.exit(1)

    # Ensure output directory exists
    os.makedirs(os.path.dirname(output_path), exist_ok=True)

    entries = read_pua_map(csv_path)
    if not entries:
        print("Error: No entries found in PUA map CSV.", file=sys.stderr)
        sys.exit(1)

    count = generate_dict_yaml(entries, output_path)
    print(f"Generated {output_path}")
    print(f"  {count} dictionary entries written")


if __name__ == "__main__":
    main()
