#!/usr/bin/env python3
"""
Convert a Rime .dict.yaml to HeliBoard word list format.

Reads the Rime dictionary (rime/one.dict.yaml), extracts entries, and
outputs a CSV word list compatible with HeliBoard's custom dictionary import.

HeliBoard word list format:
    word=<text>,f=<frequency>,originalFreq=<frequency>

Usage:
    python scripts/rime_to_heliboard_dict.py [input_path] [output_path]

Defaults:
    input:  rime/one.dict.yaml
    output: android/heliboard-config/one_wordlist.csv
"""

import os
import sys


def find_repo_root():
    """Walk up from the script location to find the repository root."""
    current = os.path.dirname(os.path.abspath(__file__))
    while current != os.path.dirname(current):
        if os.path.isfile(os.path.join(current, "README.md")) and os.path.isdir(
            os.path.join(current, "rime")
        ):
            return current
        current = os.path.dirname(current)
    print("Error: Could not locate repository root.", file=sys.stderr)
    sys.exit(1)


def parse_rime_dict(dict_path):
    """Parse a Rime dictionary YAML file and extract entries.

    Returns a list of dicts with keys: text, code, weight.
    Handles the YAML header delimited by --- and ... markers.
    """
    entries = []
    header_ended = False
    in_header = False

    with open(dict_path, "r", encoding="utf-8") as f:
        for line in f:
            stripped = line.rstrip("\n\r")

            # Skip comments and blank lines
            if stripped.startswith("#") or stripped == "":
                continue

            # Track YAML header
            if stripped == "---" and not in_header:
                in_header = True
                continue
            if stripped == "..." and in_header:
                in_header = False
                header_ended = True
                continue

            if in_header:
                continue

            if header_ended:
                parts = stripped.split("\t")
                if len(parts) >= 2:
                    entry = {
                        "text": parts[0],
                        "code": parts[1],
                        "weight": int(parts[2]) if len(parts) > 2 else 1,
                    }
                    entries.append(entry)

    return entries


def convert_to_heliboard(entries, output_path, max_frequency=255):
    """Write entries in HeliBoard word list CSV format.

    HeliBoard frequency range is 1-255. We scale the Rime weights
    proportionally to fit this range.
    """
    if not entries:
        print("Warning: No entries to convert.", file=sys.stderr)
        return 0

    # Find weight range for scaling
    max_weight = max(e["weight"] for e in entries)
    min_weight = min(e["weight"] for e in entries)
    weight_range = max_weight - min_weight if max_weight != min_weight else 1

    lines = [
        "# HeliBoard word list for CircleOne (isiBheqe soHlamvu)",
        "# Auto-generated by scripts/rime_to_heliboard_dict.py",
        "# Format: word=<glyph>,f=<frequency>,originalFreq=<frequency>",
        "",
    ]

    for entry in entries:
        # Scale weight to HeliBoard frequency range (1-255)
        scaled = int(
            ((entry["weight"] - min_weight) / weight_range) * (max_frequency - 1) + 1
        )
        scaled = max(1, min(max_frequency, scaled))

        lines.append(
            f" word={entry['text']},f={scaled},originalFreq={scaled}"
        )

    # Ensure output directory exists
    os.makedirs(os.path.dirname(output_path), exist_ok=True)

    with open(output_path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
        f.write("\n")

    return len(entries)


def main():
    repo_root = find_repo_root()

    input_path = (
        sys.argv[1]
        if len(sys.argv) > 1
        else os.path.join(repo_root, "rime", "one.dict.yaml")
    )
    output_path = (
        sys.argv[2]
        if len(sys.argv) > 2
        else os.path.join(repo_root, "android", "heliboard-config", "one_wordlist.csv")
    )

    if not os.path.isfile(input_path):
        print(f"Error: Input file not found: {input_path}", file=sys.stderr)
        sys.exit(1)

    print(f"Reading Rime dictionary: {input_path}")
    entries = parse_rime_dict(input_path)

    if not entries:
        print("Error: No entries found in Rime dictionary.", file=sys.stderr)
        sys.exit(1)

    print(f"  Found {len(entries)} entries")

    count = convert_to_heliboard(entries, output_path)
    print(f"Wrote HeliBoard word list: {output_path}")
    print(f"  {count} entries converted")


if __name__ == "__main__":
    main()
